// Generated by scripts/generate-guides.mjs. Do not edit by hand.

export type GuideLink = {
  title: string;
  description: string;
  canonicalPath: string;
  category: string;
  slug: string;
  topics: string[];
};

export const GUIDES: GuideLink[] = [
  {
    "title": "ALB vs NLB cost: how to choose and estimate (LCU vs NLCU)",
    "description": "Compare ALB vs NLB cost with a practical checklist: fixed hourly fees, LCU vs NLCU drivers, traffic patterns, and when each tends to win.",
    "canonicalPath": "/guides/aws-alb-vs-nlb-cost",
    "category": "AWS",
    "slug": "aws-alb-vs-nlb-cost",
    "topics": [
      "load-balancing"
    ]
  },
  {
    "title": "API Gateway access logs cost: how to estimate ingestion and retention",
    "description": "A practical guide to estimate API Gateway access logs cost: estimate average bytes per request, convert to GB/day, model retention (GB-month), and reduce log spend safely.",
    "canonicalPath": "/guides/aws-api-gateway-access-logs-cost",
    "category": "AWS",
    "slug": "aws-api-gateway-access-logs-cost",
    "topics": [
      "backup",
      "logging",
      "requests"
    ]
  },
  {
    "title": "API Gateway cost optimization: reduce requests, bytes, and log spend",
    "description": "A practical playbook to reduce API Gateway spend: identify the dominant driver (requests, transfer, or logs), then apply high-leverage fixes with a validation checklist.",
    "canonicalPath": "/guides/aws-api-gateway-cost-optimization",
    "category": "AWS",
    "slug": "aws-api-gateway-cost-optimization",
    "topics": [
      "egress",
      "logging",
      "requests"
    ]
  },
  {
    "title": "API Gateway pricing: what to model (requests + transfer)",
    "description": "A practical API Gateway pricing checklist: request charges, data transfer, and the add-ons that can show up on the bill.",
    "canonicalPath": "/guides/aws-api-gateway-pricing",
    "category": "AWS",
    "slug": "aws-api-gateway-pricing",
    "topics": [
      "egress",
      "requests"
    ]
  },
  {
    "title": "API Gateway vs ALB vs CloudFront cost: what to compare (requests, transfer, add-ons)",
    "description": "A practical cost comparison of API Gateway, Application Load Balancer (ALB), and CloudFront. Compare request pricing, data transfer, caching impact, WAF, logs, and the hidden line items that change the answer.",
    "canonicalPath": "/guides/aws-api-gateway-vs-alb-vs-cloudfront-cost",
    "category": "AWS",
    "slug": "aws-api-gateway-vs-alb-vs-cloudfront-cost",
    "topics": [
      "cdn",
      "egress",
      "load-balancing",
      "logging",
      "requests",
      "security"
    ]
  },
  {
    "title": "Aurora pricing (what to include): compute, storage, I/O, and backups",
    "description": "A practical checklist for estimating Aurora costs: instance hours (or ACUs), storage growth, I/O-heavy workloads, backups/retention, and the line items that commonly surprise budgets.",
    "canonicalPath": "/guides/aws-aurora-pricing",
    "category": "AWS",
    "slug": "aws-aurora-pricing",
    "topics": [
      "backup",
      "compute",
      "database",
      "storage"
    ]
  },
  {
    "title": "Aurora Serverless v2 pricing: how to estimate ACUs and avoid surprise bills",
    "description": "A practical way to estimate Aurora Serverless v2 costs: ACU-hours, storage GB-month, backups/retention, and how to model peaks so your estimate survives real traffic.",
    "canonicalPath": "/guides/aws-aurora-serverless-v2-pricing",
    "category": "AWS",
    "slug": "aws-aurora-serverless-v2-pricing",
    "topics": [
      "backup",
      "database",
      "kubernetes",
      "serverless",
      "storage"
    ]
  },
  {
    "title": "AWS cost checklist: model the drivers that actually move the bill",
    "description": "A practical AWS cost checklist for planning and reviews: define scope, identify top cost drivers (requests, GB, GB-month, hours), and avoid the common blind spots (data transfer, logs, and cross-AZ).",
    "canonicalPath": "/guides/aws-cost-checklist",
    "category": "AWS",
    "slug": "aws-cost-checklist",
    "topics": [
      "egress",
      "logging",
      "requests"
    ]
  },
  {
    "title": "AWS Lambda cost optimization (high-leverage fixes)",
    "description": "A practical Lambda cost optimization checklist: reduce GB-seconds (duration × memory), control retries, right-size concurrency, and avoid hidden logging and networking costs.",
    "canonicalPath": "/guides/aws-lambda-cost-optimization",
    "category": "AWS",
    "slug": "aws-lambda-cost-optimization",
    "topics": [
      "logging",
      "serverless"
    ]
  },
  {
    "title": "AWS Lambda pricing (what to include)",
    "description": "A practical checklist for estimating AWS Lambda-style costs: requests, duration × memory (GB-seconds), provisioned concurrency when used, logs, and common hidden line items.",
    "canonicalPath": "/guides/aws-lambda-pricing",
    "category": "AWS",
    "slug": "aws-lambda-pricing",
    "topics": [
      "logging",
      "requests",
      "serverless"
    ]
  },
  {
    "title": "AWS network cost guide: NAT, VPC endpoints, PrivateLink, and data transfer (what to model)",
    "description": "A practical AWS network cost hub: how to model NAT Gateway, VPC endpoints/PrivateLink, and cross-AZ/cross-region data transfer. Includes formulas, break-even workflow, and a troubleshooting checklist.",
    "canonicalPath": "/guides/aws-network-costs",
    "category": "AWS",
    "slug": "aws-network-costs",
    "topics": [
      "egress",
      "requests"
    ]
  },
  {
    "title": "AWS PrivateLink pricing: what to model (consumer vs provider)",
    "description": "A practical PrivateLink pricing checklist: interface endpoint-hours, per-GB processing, and provider-side considerations. Includes the transfer pitfalls that cause surprise bills.",
    "canonicalPath": "/guides/aws-privatelink-pricing",
    "category": "AWS",
    "slug": "aws-privatelink-pricing",
    "topics": [
      "egress"
    ]
  },
  {
    "title": "AWS RDS cost optimization (high-leverage fixes)",
    "description": "A short playbook to reduce RDS cost: right-size instances, control storage growth, tune backups, and avoid expensive I/O patterns.",
    "canonicalPath": "/guides/aws-rds-cost-optimization",
    "category": "AWS",
    "slug": "aws-rds-cost-optimization",
    "topics": [
      "backup",
      "compute",
      "database",
      "storage"
    ]
  },
  {
    "title": "AWS RDS pricing (what to include)",
    "description": "A practical checklist for estimating AWS RDS costs: instances, storage, backups, I/O, and the line items that commonly surprise budgets.",
    "canonicalPath": "/guides/aws-rds-pricing",
    "category": "AWS",
    "slug": "aws-rds-pricing",
    "topics": [
      "backup",
      "compute",
      "database",
      "storage"
    ]
  },
  {
    "title": "AWS SQS cost optimization (high-leverage fixes)",
    "description": "A practical playbook to reduce SQS costs: reduce requests per successful message with batching and long polling, prevent retry storms and poison loops, and validate savings with sent/received/deleted metrics.",
    "canonicalPath": "/guides/aws-sqs-cost-optimization",
    "category": "AWS",
    "slug": "aws-sqs-cost-optimization",
    "topics": [
      "messaging",
      "metrics",
      "requests"
    ]
  },
  {
    "title": "AWS SQS pricing (what to include)",
    "description": "A practical checklist for estimating SQS costs: requests, retries, Receive/Delete patterns, and the common pitfalls that inflate spend.",
    "canonicalPath": "/guides/aws-sqs-pricing",
    "category": "AWS",
    "slug": "aws-sqs-pricing",
    "topics": [
      "messaging",
      "requests"
    ]
  },
  {
    "title": "AWS WAF pricing: what to model (ACLs, rules, requests)",
    "description": "A practical AWS WAF pricing checklist: Web ACL fees, rule fees, request charges, and the downstream costs security teams forget.",
    "canonicalPath": "/guides/aws-waf-pricing",
    "category": "AWS",
    "slug": "aws-waf-pricing",
    "topics": [
      "requests",
      "security"
    ]
  },
  {
    "title": "AWS WAF vs Cloudflare WAF cost: a practical comparison checklist",
    "description": "Compare AWS WAF vs Cloudflare WAF cost using a practical checklist: request-based charges, rule/policy baselines, logging/analytics costs, and what to model for your traffic shape.",
    "canonicalPath": "/guides/aws-waf-vs-cloudflare-waf-cost",
    "category": "AWS",
    "slug": "aws-waf-vs-cloudflare-waf-cost",
    "topics": [
      "logging",
      "requests",
      "security"
    ]
  },
  {
    "title": "CloudFront cache hit rate: how it changes origin egress cost",
    "description": "Cache hit rate strongly influences origin requests and origin egress (cache fill). Learn a simple model, what breaks hit rate, and the practical levers to improve it safely.",
    "canonicalPath": "/guides/aws-cloudfront-cache-hit-rate",
    "category": "AWS",
    "slug": "aws-cloudfront-cache-hit-rate",
    "topics": [
      "cdn",
      "egress",
      "kubernetes",
      "requests"
    ]
  },
  {
    "title": "CloudFront invalidation pricing: when it matters and how to estimate",
    "description": "A practical guide to CloudFront invalidation costs: what to count, why broad invalidations reduce cache hit rate, and safer cache-busting patterns that avoid repeated invalidations.",
    "canonicalPath": "/guides/aws-cloudfront-invalidation-pricing",
    "category": "AWS",
    "slug": "aws-cloudfront-invalidation-pricing",
    "topics": [
      "cdn"
    ]
  },
  {
    "title": "CloudFront logs cost: estimate storage, retention, and queries",
    "description": "How to estimate CloudFront log costs: log volume (GB/day), retention (GB-month), and downstream query/scan costs (Athena/SIEM). Includes practical cost-control levers.",
    "canonicalPath": "/guides/aws-cloudfront-logs-cost",
    "category": "AWS",
    "slug": "aws-cloudfront-logs-cost",
    "topics": [
      "backup",
      "cdn",
      "logging",
      "storage"
    ]
  },
  {
    "title": "CloudFront pricing: estimate bandwidth and request costs (without hardcoding prices)",
    "description": "A practical way to estimate CloudFront-style CDN costs using your own bandwidth ($/GB) and request-fee ($ per 10k/1M) assumptions, plus common pitfalls like tiered pricing and origin egress.",
    "canonicalPath": "/guides/aws-cloudfront-pricing",
    "category": "AWS",
    "slug": "aws-cloudfront-pricing",
    "topics": [
      "cdn",
      "egress",
      "requests"
    ]
  },
  {
    "title": "CloudTrail cost optimization (reduce high-volume drivers)",
    "description": "A practical playbook to reduce CloudTrail costs: measure event volume, control data event scope with selectors, reduce automated churn, and avoid downstream storage/query waste.",
    "canonicalPath": "/guides/aws-cloudtrail-cost-optimization",
    "category": "AWS",
    "slug": "aws-cloudtrail-cost-optimization",
    "topics": [
      "storage"
    ]
  },
  {
    "title": "CloudTrail pricing: what to model (management vs data events)",
    "description": "A practical CloudTrail pricing checklist: separate management, data, and Insights events, then add downstream storage and query costs for your audit log pipeline.",
    "canonicalPath": "/guides/aws-cloudtrail-pricing",
    "category": "AWS",
    "slug": "aws-cloudtrail-pricing",
    "topics": [
      "logging",
      "metrics",
      "storage"
    ]
  },
  {
    "title": "CloudWatch alarms cost optimization: reduce alarm-month waste",
    "description": "A practical playbook to reduce CloudWatch alarm costs: find unused alarms, avoid per-resource duplication, choose resolution intentionally, and validate changes safely.",
    "canonicalPath": "/guides/aws-cloudwatch-alarms-cost-optimization",
    "category": "AWS",
    "slug": "aws-cloudwatch-alarms-cost-optimization",
    "topics": [
      "logging"
    ]
  },
  {
    "title": "CloudWatch alarms pricing: what to model (alarm-month by type)",
    "description": "A practical CloudWatch alarms pricing checklist: model alarm-month charges by alarm type (standard, high-resolution, composite), include notifications, and avoid common estimation mistakes.",
    "canonicalPath": "/guides/aws-cloudwatch-alarms-pricing",
    "category": "AWS",
    "slug": "aws-cloudwatch-alarms-pricing",
    "topics": [
      "logging"
    ]
  },
  {
    "title": "CloudWatch dashboards pricing: what to include (dashboard-month + API)",
    "description": "A practical guide to CloudWatch dashboard costs: dashboard-month charges plus the hidden drivers (metrics API requests, alarms, and high-cardinality metrics).",
    "canonicalPath": "/guides/aws-cloudwatch-dashboards-pricing",
    "category": "AWS",
    "slug": "aws-cloudwatch-dashboards-pricing",
    "topics": [
      "database",
      "logging",
      "metrics",
      "requests"
    ]
  },
  {
    "title": "CloudWatch Logs Insights cost optimization (reduce GB scanned)",
    "description": "A practical playbook to reduce CloudWatch Logs Insights costs: measure GB scanned, fix query patterns, time-bound dashboards, and avoid repeated incident scans.",
    "canonicalPath": "/guides/aws-cloudwatch-logs-insights-cost-optimization",
    "category": "AWS",
    "slug": "aws-cloudwatch-logs-insights-cost-optimization",
    "topics": [
      "database",
      "logging",
      "metrics"
    ]
  },
  {
    "title": "CloudWatch Logs Insights pricing: what to model (GB scanned)",
    "description": "A practical Logs Insights pricing checklist: the core unit is GB scanned. Model scanned GB from query habits, avoid dashboard re-scan traps, and validate with a measured baseline.",
    "canonicalPath": "/guides/aws-cloudwatch-logs-insights-pricing",
    "category": "AWS",
    "slug": "aws-cloudwatch-logs-insights-pricing",
    "topics": [
      "logging",
      "metrics"
    ]
  },
  {
    "title": "CloudWatch Logs pricing: ingestion, retention, and queries",
    "description": "A practical CloudWatch Logs pricing guide: model ingestion (GB/day), retention (GB-month), and query/scan costs (Insights/Athena). Includes pitfalls and a validation checklist.",
    "canonicalPath": "/guides/aws-cloudwatch-logs-pricing",
    "category": "AWS",
    "slug": "aws-cloudwatch-logs-pricing",
    "topics": [
      "backup",
      "logging",
      "metrics"
    ]
  },
  {
    "title": "CloudWatch metrics cost optimization: reduce custom metric sprawl",
    "description": "A practical playbook to reduce CloudWatch metrics costs: control custom metric cardinality, right-size resolution, reduce API polling, and validate observability coverage.",
    "canonicalPath": "/guides/aws-cloudwatch-metrics-cost-optimization",
    "category": "AWS",
    "slug": "aws-cloudwatch-metrics-cost-optimization",
    "topics": [
      "logging",
      "metrics",
      "requests"
    ]
  },
  {
    "title": "CloudWatch metrics pricing: what to model (metrics + API + dashboards)",
    "description": "A practical CloudWatch metrics pricing checklist: custom metric time series, high-cardinality dimensions, metrics API requests, dashboards, and alarms. Includes a fast modeling workflow and pitfalls.",
    "canonicalPath": "/guides/aws-cloudwatch-metrics-pricing",
    "category": "AWS",
    "slug": "aws-cloudwatch-metrics-pricing",
    "topics": [
      "database",
      "logging",
      "metrics",
      "requests"
    ]
  },
  {
    "title": "Cross-AZ data transfer cost (AWS): what causes it and how to estimate",
    "description": "A practical guide to cross-AZ data transfer costs: common causes (load balancers, databases, Kubernetes), how to estimate GB crossing zones, and how to reduce it safely.",
    "canonicalPath": "/guides/aws-cross-az-data-transfer-cost",
    "category": "AWS",
    "slug": "aws-cross-az-data-transfer-cost",
    "topics": [
      "database",
      "egress",
      "kubernetes",
      "load-balancing"
    ]
  },
  {
    "title": "DynamoDB cost optimization: reduce read/write and storage drivers",
    "description": "A practical playbook to reduce DynamoDB spend: fix access patterns, reduce item size, avoid scan-heavy queries, control index amplification, and validate changes safely.",
    "canonicalPath": "/guides/aws-dynamodb-cost-optimization",
    "category": "AWS",
    "slug": "aws-dynamodb-cost-optimization",
    "topics": [
      "storage"
    ]
  },
  {
    "title": "DynamoDB pricing: what to model (reads, writes, storage, extras)",
    "description": "A practical DynamoDB pricing checklist: model reads and writes (RCU/WCU), storage (GB-month), and the common add-ons (backups, streams, global tables). Includes pitfalls and validation steps.",
    "canonicalPath": "/guides/aws-dynamodb-pricing",
    "category": "AWS",
    "slug": "aws-dynamodb-pricing",
    "topics": [
      "backup",
      "storage"
    ]
  },
  {
    "title": "DynamoDB RCU/WCU explained (with sizing examples)",
    "description": "A practical explanation of DynamoDB read and write capacity units (RCU/WCU): how item size affects units, how to estimate from requests, and the pitfalls that make estimates wrong.",
    "canonicalPath": "/guides/aws-dynamodb-rcu-wcu-explained",
    "category": "AWS",
    "slug": "aws-dynamodb-rcu-wcu-explained",
    "topics": [
      "requests"
    ]
  },
  {
    "title": "EBS cost optimization: volumes, IOPS/throughput, and snapshots",
    "description": "A practical playbook to reduce EBS spend: right-size volume GB, choose the right volume type (gp2 vs gp3), avoid over-provisioned IOPS/throughput, and control snapshot growth safely.",
    "canonicalPath": "/guides/aws-ebs-cost-optimization",
    "category": "AWS",
    "slug": "aws-ebs-cost-optimization",
    "topics": [
      "backup"
    ]
  },
  {
    "title": "EBS pricing: what to model (storage, performance, snapshots)",
    "description": "A practical EBS pricing checklist: volume GB-month, provisioned IOPS/throughput (when applicable), snapshot storage, and the operational patterns that create cost spikes.",
    "canonicalPath": "/guides/aws-ebs-pricing",
    "category": "AWS",
    "slug": "aws-ebs-pricing",
    "topics": [
      "backup",
      "storage"
    ]
  },
  {
    "title": "EBS snapshot cost: how to estimate storage from change rate",
    "description": "A practical guide to estimate EBS snapshot storage: incremental snapshots, daily change rate, retention, copies, and a workflow to validate estimates against real data.",
    "canonicalPath": "/guides/aws-ebs-snapshot-cost",
    "category": "AWS",
    "slug": "aws-ebs-snapshot-cost",
    "topics": [
      "backup",
      "storage"
    ]
  },
  {
    "title": "EC2 cost estimation: a practical model (compute + the hidden line items)",
    "description": "A practical EC2 cost estimation guide: model instance-hours with uptime and blended rates, then add the hidden line items that often dominate (EBS, snapshots, load balancers, NAT/egress, logs).",
    "canonicalPath": "/guides/aws-ec2-cost-estimation",
    "category": "AWS",
    "slug": "aws-ec2-cost-estimation",
    "topics": [
      "backup",
      "compute",
      "egress",
      "load-balancing",
      "logging"
    ]
  },
  {
    "title": "ECR cost optimization: retention, smaller images, fewer pulls",
    "description": "A high-leverage playbook to reduce AWS ECR cost: enforce retention, shrink images, reduce redundant pulls in CI and clusters, and validate savings without breaking rollbacks.",
    "canonicalPath": "/guides/aws-ecr-cost-optimization",
    "category": "AWS",
    "slug": "aws-ecr-cost-optimization",
    "topics": [
      "backup",
      "storage"
    ]
  },
  {
    "title": "ECR pricing: what to model (storage + transfer)",
    "description": "A practical AWS ECR pricing checklist: storage (GB-month), image pull transfer across network boundaries, and the operational patterns that create cost spikes (retention, CI rebuilds, multi-arch).",
    "canonicalPath": "/guides/aws-ecr-pricing",
    "category": "AWS",
    "slug": "aws-ecr-pricing",
    "topics": [
      "backup",
      "egress",
      "storage"
    ]
  },
  {
    "title": "ECS autoscaling cost pitfalls (and how to avoid them)",
    "description": "A practical guide to ECS autoscaling cost pitfalls: noisy signals, oscillations, retry storms, and the non-compute line items that scale with traffic (logs, NAT/egress, load balancers).",
    "canonicalPath": "/guides/aws-ecs-autoscaling-cost-pitfalls",
    "category": "AWS",
    "slug": "aws-ecs-autoscaling-cost-pitfalls",
    "topics": [
      "compute",
      "egress",
      "load-balancing",
      "logging"
    ]
  },
  {
    "title": "ECS cost model beyond compute: the checklist that prevents surprise bills",
    "description": "A practical ECS cost model checklist beyond compute: load balancers, logs/metrics, NAT/egress, cross-AZ transfer, storage, and image registry behavior. Use it to avoid underestimating total ECS cost.",
    "canonicalPath": "/guides/aws-ecs-cost-model-beyond-compute",
    "category": "AWS",
    "slug": "aws-ecs-cost-model-beyond-compute",
    "topics": [
      "compute",
      "egress",
      "load-balancing",
      "logging",
      "metrics",
      "storage"
    ]
  },
  {
    "title": "ECS on EC2 vs ECS on Fargate cost: a practical decision checklist",
    "description": "Compare ECS on EC2 vs ECS on Fargate cost with a practical checklist: utilization, packing efficiency, idle capacity, and the non-compute line items that often decide the winner.",
    "canonicalPath": "/guides/aws-ecs-ec2-vs-fargate-cost",
    "category": "AWS",
    "slug": "aws-ecs-ec2-vs-fargate-cost",
    "topics": [
      "compute",
      "serverless"
    ]
  },
  {
    "title": "ECS pricing: what to include in a realistic cost model",
    "description": "A practical ECS pricing guide: how costs differ between EC2 launch type and Fargate launch type, and what line items you must include (compute, load balancers, logs, transfer, storage, registry behavior).",
    "canonicalPath": "/guides/aws-ecs-pricing",
    "category": "AWS",
    "slug": "aws-ecs-pricing",
    "topics": [
      "compute",
      "egress",
      "load-balancing",
      "logging",
      "serverless",
      "storage"
    ]
  },
  {
    "title": "ECS task sizing: how to pick CPU and memory (and estimate task count)",
    "description": "A practical ECS task sizing guide: choose vCPU/memory from measured usage, pick a utilization target, estimate average task count, and avoid the sizing mistakes that cause cost spikes.",
    "canonicalPath": "/guides/aws-ecs-task-sizing",
    "category": "AWS",
    "slug": "aws-ecs-task-sizing",
    "topics": []
  },
  {
    "title": "ECS vs EKS cost: a practical checklist (compute, overhead, and add-ons)",
    "description": "Compare ECS vs EKS cost with a consistent checklist: compute model, platform overhead, scaling behavior, and the line items that often dominate (load balancers, logs, data transfer).",
    "canonicalPath": "/guides/aws-ecs-vs-eks-cost",
    "category": "AWS",
    "slug": "aws-ecs-vs-eks-cost",
    "topics": [
      "compute",
      "egress",
      "kubernetes",
      "load-balancing",
      "logging"
    ]
  },
  {
    "title": "EKS control plane cost: how to model it and when it matters",
    "description": "A practical guide to modeling EKS control plane costs: fixed hourly fees, multi-cluster strategy, and how to keep dev/test clusters from inflating spend.",
    "canonicalPath": "/guides/aws-eks-control-plane-cost",
    "category": "AWS",
    "slug": "aws-eks-control-plane-cost",
    "topics": [
      "kubernetes"
    ]
  },
  {
    "title": "EKS node sizing: requests, overhead, and why packing is never perfect",
    "description": "A practical EKS node sizing guide: size from requests, reserve headroom, account for DaemonSets and max-pods limits, and understand why real scheduling often needs more nodes than the math minimum.",
    "canonicalPath": "/guides/aws-eks-node-sizing",
    "category": "AWS",
    "slug": "aws-eks-node-sizing",
    "topics": [
      "kubernetes",
      "requests"
    ]
  },
  {
    "title": "EKS pricing: what to include in a realistic cost estimate",
    "description": "A practical EKS pricing checklist: nodes, control plane, load balancers, storage, logs/metrics, and data transfer — with calculators to estimate each part.",
    "canonicalPath": "/guides/aws-eks-pricing",
    "category": "AWS",
    "slug": "aws-eks-pricing",
    "topics": [
      "egress",
      "kubernetes",
      "load-balancing",
      "logging",
      "metrics",
      "storage"
    ]
  },
  {
    "title": "Estimate ALB LCU (and NLB NLCU) from metrics: quick methods",
    "description": "A practical guide to estimate ALB LCU and NLB NLCU from load balancer metrics: new connections, active connections, bytes processed, and rule evaluations — with a repeatable workflow and validation steps.",
    "canonicalPath": "/guides/aws-load-balancer-estimate-lcu",
    "category": "AWS",
    "slug": "aws-load-balancer-estimate-lcu",
    "topics": [
      "load-balancing",
      "metrics"
    ]
  },
  {
    "title": "Estimate API requests per month (RPS, logs, and metrics)",
    "description": "How to estimate monthly API request volume for cost models: from CloudWatch metrics, from access logs, and from RPS charts (with common pitfalls like retries and health checks).",
    "canonicalPath": "/guides/aws-api-gateway-estimate-requests",
    "category": "AWS",
    "slug": "aws-api-gateway-estimate-requests",
    "topics": [
      "logging",
      "metrics",
      "requests"
    ]
  },
  {
    "title": "Estimate CloudTrail events per month (practical methods)",
    "description": "How to estimate CloudTrail event volume for cost models: count from CloudTrail Lake or S3-delivered logs, split management vs data events, and include retries and automation.",
    "canonicalPath": "/guides/aws-cloudtrail-estimate-events",
    "category": "AWS",
    "slug": "aws-cloudtrail-estimate-events",
    "topics": [
      "logging",
      "storage"
    ]
  },
  {
    "title": "Estimate CloudWatch alarm count (standard, high-res, composite)",
    "description": "How to estimate CloudWatch alarm-month charges: count alarms by type (standard, high-resolution, composite), include ephemeral environments, and validate with inventory methods.",
    "canonicalPath": "/guides/aws-cloudwatch-alarms-estimate-alarm-count",
    "category": "AWS",
    "slug": "aws-cloudwatch-alarms-estimate-alarm-count",
    "topics": [
      "logging"
    ]
  },
  {
    "title": "Estimate CloudWatch custom metrics (time series count)",
    "description": "How to estimate CloudWatch custom metric volume for cost models: count unique time series (metric name * dimension combinations), model high-cardinality dimensions, and validate with inventory methods.",
    "canonicalPath": "/guides/aws-cloudwatch-metrics-estimate-custom-metrics",
    "category": "AWS",
    "slug": "aws-cloudwatch-metrics-estimate-custom-metrics",
    "topics": [
      "logging",
      "metrics"
    ]
  },
  {
    "title": "Estimate CloudWatch metrics API requests (dashboards and polling)",
    "description": "How to estimate CloudWatch metrics API request volume for cost models: derive requests from dashboards and tooling polling, include refresh rates, and validate with measured usage.",
    "canonicalPath": "/guides/aws-cloudwatch-metrics-estimate-api-requests",
    "category": "AWS",
    "slug": "aws-cloudwatch-metrics-estimate-api-requests",
    "topics": [
      "database",
      "logging",
      "metrics",
      "requests"
    ]
  },
  {
    "title": "Estimate DNS queries per month (Route 53 query volume)",
    "description": "How to estimate DNS query volume for Route 53 cost models: from metrics and logs, and what drives query spikes (TTL, retries, resolver behavior).",
    "canonicalPath": "/guides/aws-route-53-estimate-dns-queries",
    "category": "AWS",
    "slug": "aws-route-53-estimate-dns-queries",
    "topics": [
      "logging",
      "metrics"
    ]
  },
  {
    "title": "Estimate ECR storage (GB-month) from images and retention",
    "description": "How to estimate container registry storage cost: average image size, push frequency, retention window, multi-arch duplication, and a workflow to validate your estimate.",
    "canonicalPath": "/guides/aws-ecr-estimate-storage-gb-month",
    "category": "AWS",
    "slug": "aws-ecr-estimate-storage-gb-month",
    "topics": [
      "backup",
      "compute",
      "storage"
    ]
  },
  {
    "title": "Estimate email volume per month (transactional + marketing)",
    "description": "A practical workflow to estimate monthly email volume for SES cost models: derive transactional volume from user actions, campaign volume from calendars, and add a defendable retry/duplicate factor for incident spikes.",
    "canonicalPath": "/guides/aws-ses-estimate-email-volume",
    "category": "AWS",
    "slug": "aws-ses-estimate-email-volume",
    "topics": []
  },
  {
    "title": "Estimate Glacier/Deep Archive retrieval volume (GB and requests)",
    "description": "How to estimate archival retrieval costs: model GB restored per month and the number of objects retrieved (requests), plus common drivers like restores, rehydration, and analytics.",
    "canonicalPath": "/guides/aws-s3-glacier-estimate-retrieval",
    "category": "AWS",
    "slug": "aws-s3-glacier-estimate-retrieval",
    "topics": [
      "requests",
      "storage"
    ]
  },
  {
    "title": "Estimate KMS requests per month (where they come from)",
    "description": "A practical workflow to estimate AWS KMS request volume: identify call sources, translate workload volume into KMS API calls, and validate with billing/CloudTrail so you can budget and optimize safely.",
    "canonicalPath": "/guides/aws-kms-estimate-requests",
    "category": "AWS",
    "slug": "aws-kms-estimate-requests",
    "topics": [
      "requests",
      "security"
    ]
  },
  {
    "title": "Estimate Logs Insights scanned GB (from query habits)",
    "description": "How to estimate CloudWatch Logs Insights cost: model GB scanned per query, query frequency, and time range. Includes a quick calculator workflow and common pitfalls.",
    "canonicalPath": "/guides/aws-cloudwatch-logs-insights-estimate-scanned-gb",
    "category": "AWS",
    "slug": "aws-cloudwatch-logs-insights-estimate-scanned-gb",
    "topics": [
      "logging",
      "metrics"
    ]
  },
  {
    "title": "Estimate NAT Gateway GB processed (quick methods)",
    "description": "Practical ways to estimate NAT Gateway GB processed per month: from NAT metrics, from VPC Flow Logs, from Mbps charts, and from common traffic sources — with validation tips so your budget holds up.",
    "canonicalPath": "/guides/aws-nat-gateway-estimate-gb-processed",
    "category": "AWS",
    "slug": "aws-nat-gateway-estimate-gb-processed",
    "topics": [
      "logging",
      "metrics",
      "requests"
    ]
  },
  {
    "title": "Estimate Parameter Store API calls per month (GetParameter volume)",
    "description": "How to estimate SSM Parameter Store API call volume for cost models: measure from billing/logs, derive from runtime patterns, and account for deploy + churn multipliers.",
    "canonicalPath": "/guides/aws-ssm-parameter-store-estimate-api-calls",
    "category": "AWS",
    "slug": "aws-ssm-parameter-store-estimate-api-calls",
    "topics": [
      "logging",
      "requests"
    ]
  },
  {
    "title": "Estimate RDS backup storage (GB-month) from retention and churn",
    "description": "A practical method to estimate RDS backup storage (GB-month): start from daily changed data, retention days, and sanity-check with snapshot sizes. Includes common mistakes that inflate backup cost.",
    "canonicalPath": "/guides/aws-rds-backup-storage-gb-month-estimate",
    "category": "AWS",
    "slug": "aws-rds-backup-storage-gb-month-estimate",
    "topics": [
      "backup",
      "database",
      "storage"
    ]
  },
  {
    "title": "Estimate Secrets Manager API calls per month (GetSecretValue volume)",
    "description": "A practical workflow to estimate Secrets Manager API request volume (especially GetSecretValue): measure and scale when possible, model from runtime churn when not, and validate with CloudTrail so your budget survives peaks.",
    "canonicalPath": "/guides/aws-secrets-manager-estimate-api-calls",
    "category": "AWS",
    "slug": "aws-secrets-manager-estimate-api-calls",
    "topics": [
      "kubernetes",
      "requests",
      "storage"
    ]
  },
  {
    "title": "Estimate SNS deliveries per month (messages x subscribers)",
    "description": "A practical workflow to estimate SNS delivery volume: start from publishes, model matched fan-out (after filter policies), add a retry multiplier for failures, and validate with metrics so budgets survive incidents.",
    "canonicalPath": "/guides/aws-sns-estimate-deliveries",
    "category": "AWS",
    "slug": "aws-sns-estimate-deliveries",
    "topics": [
      "messaging",
      "metrics"
    ]
  },
  {
    "title": "Estimate SQS requests (from messages and retries)",
    "description": "A practical workflow to estimate billable SQS request volume: start from messages/month, model requests per successful message (Send/Receive/Delete), and add the multipliers (retries, empty receives, poison loops) that cause spikes.",
    "canonicalPath": "/guides/aws-sqs-estimate-requests",
    "category": "AWS",
    "slug": "aws-sqs-estimate-requests",
    "topics": [
      "messaging",
      "requests"
    ]
  },
  {
    "title": "Estimate VPC endpoint cost inputs: endpoint-hours and GB processed",
    "description": "How to estimate VPC interface endpoint (PrivateLink) cost inputs: count endpoints across AZs, estimate monthly hours, and estimate GB processed from NAT metrics, flow logs, or scenario models.",
    "canonicalPath": "/guides/aws-vpc-endpoints-estimate-hours-and-gb",
    "category": "AWS",
    "slug": "aws-vpc-endpoints-estimate-hours-and-gb",
    "topics": [
      "logging",
      "metrics",
      "storage"
    ]
  },
  {
    "title": "Estimate WAF request volume (CDN/LB to monthly requests)",
    "description": "How to estimate WAF request volume for cost models: from CDN/LB metrics, from logs, and what to do about bot spikes.",
    "canonicalPath": "/guides/aws-waf-estimate-requests",
    "category": "AWS",
    "slug": "aws-waf-estimate-requests",
    "topics": [
      "cdn",
      "logging",
      "metrics",
      "requests",
      "security"
    ]
  },
  {
    "title": "Fargate cost optimization (high-leverage fixes)",
    "description": "A practical Fargate cost optimization checklist: rightsize tasks, scale on real signals, reduce idle capacity, and avoid hidden networking and logging costs.",
    "canonicalPath": "/guides/aws-fargate-cost-optimization",
    "category": "AWS",
    "slug": "aws-fargate-cost-optimization",
    "topics": [
      "compute",
      "logging",
      "serverless"
    ]
  },
  {
    "title": "Fargate pricing (what to include in your cost model)",
    "description": "A practical Fargate pricing guide: what drives compute cost (vCPU-hours + GB-hours), how to estimate average running tasks, and the non-compute line items that usually matter (logs, load balancers, data transfer).",
    "canonicalPath": "/guides/aws-fargate-pricing",
    "category": "AWS",
    "slug": "aws-fargate-pricing",
    "topics": [
      "compute",
      "egress",
      "load-balancing",
      "logging",
      "serverless"
    ]
  },
  {
    "title": "Fargate vs EC2 cost: how to compare compute, overhead, and hidden line items",
    "description": "A practical Fargate vs EC2 cost comparison: normalize workload assumptions, compare unit economics (vCPU/memory-hours vs instance-hours), and include the line items that change the answer (idle capacity, load balancers, logs, transfer).",
    "canonicalPath": "/guides/aws-fargate-vs-ec2-cost",
    "category": "AWS",
    "slug": "aws-fargate-vs-ec2-cost",
    "topics": [
      "compute",
      "egress",
      "load-balancing",
      "logging",
      "serverless"
    ]
  },
  {
    "title": "Fargate vs EKS cost: what usually decides the winner",
    "description": "A practical Fargate vs EKS cost comparison: normalize workload assumptions, compare task-hours vs node-hours, include EKS fixed overhead (cluster fee + add-ons), and account for the line items that dominate both (LBs, logs, transfer).",
    "canonicalPath": "/guides/aws-fargate-vs-eks-cost",
    "category": "AWS",
    "slug": "aws-fargate-vs-eks-cost",
    "topics": [
      "compute",
      "egress",
      "kubernetes",
      "logging",
      "serverless"
    ]
  },
  {
    "title": "Glacier/Deep Archive cost optimization (reduce restores and requests)",
    "description": "A practical playbook to reduce archival storage costs: reduce restores, reduce small-object request volume, and avoid minimum duration penalties. Includes validation steps and related tools.",
    "canonicalPath": "/guides/aws-s3-glacier-cost-optimization",
    "category": "AWS",
    "slug": "aws-s3-glacier-cost-optimization",
    "topics": [
      "requests",
      "storage"
    ]
  },
  {
    "title": "gp2 vs gp3 cost: how to choose (EBS)",
    "description": "A practical comparison of EBS gp2 vs gp3: how pricing and performance knobs differ, when gp3 is cheaper, and what to validate before switching.",
    "canonicalPath": "/guides/aws-ebs-gp2-vs-gp3-cost",
    "category": "AWS",
    "slug": "aws-ebs-gp2-vs-gp3-cost",
    "topics": []
  },
  {
    "title": "gp3 IOPS and throughput: how to size (EBS)",
    "description": "A practical guide to sizing EBS gp3 performance: choose IOPS and throughput from measured utilization, avoid over-provisioning, and validate latency under realistic load.",
    "canonicalPath": "/guides/aws-ebs-gp3-iops-throughput",
    "category": "AWS",
    "slug": "aws-ebs-gp3-iops-throughput",
    "topics": []
  },
  {
    "title": "How to reduce logging and observability costs (without losing signal)",
    "description": "Practical techniques to reduce log and metrics costs: source-side filtering, sampling, retention strategy, and label/cardinality hygiene — with calculators to quantify savings and a validation checklist.",
    "canonicalPath": "/guides/aws-logging-cost-reduction",
    "category": "AWS",
    "slug": "aws-logging-cost-reduction",
    "topics": [
      "backup",
      "logging",
      "metrics"
    ]
  },
  {
    "title": "KMS cost optimization (reduce request volume safely)",
    "description": "A practical AWS KMS cost optimization checklist focused on the real driver: request volume. Learn where KMS calls come from, how to reduce them safely with caching and batching, and how to validate savings.",
    "canonicalPath": "/guides/aws-kms-cost-optimization",
    "category": "AWS",
    "slug": "aws-kms-cost-optimization",
    "topics": [
      "requests",
      "security"
    ]
  },
  {
    "title": "KMS pricing: what to model (keys + requests)",
    "description": "A practical AWS KMS pricing checklist: key-months, request volume, and the services and patterns that generate surprise KMS request bills.",
    "canonicalPath": "/guides/aws-kms-pricing",
    "category": "AWS",
    "slug": "aws-kms-pricing",
    "topics": [
      "requests",
      "security"
    ]
  },
  {
    "title": "Lambda concurrency and cold starts (cost pitfalls)",
    "description": "A practical guide to Lambda concurrency and cold starts: how they affect duration and cost, when provisioned concurrency is worth it, and what to measure to avoid surprise bills.",
    "canonicalPath": "/guides/aws-lambda-concurrency-and-cold-starts",
    "category": "AWS",
    "slug": "aws-lambda-concurrency-and-cold-starts",
    "topics": [
      "serverless"
    ]
  },
  {
    "title": "Lambda vs Fargate cost: a practical comparison (unit economics)",
    "description": "Compare Lambda vs Fargate cost with unit economics: cost per 1M requests (Lambda) versus average running tasks (Fargate), plus the non-compute line items that often dominate (logs, load balancers, transfer).",
    "canonicalPath": "/guides/aws-lambda-vs-fargate-cost",
    "category": "AWS",
    "slug": "aws-lambda-vs-fargate-cost",
    "topics": [
      "compute",
      "egress",
      "load-balancing",
      "logging",
      "requests",
      "serverless"
    ]
  },
  {
    "title": "Load balancer cost optimization (high-leverage fixes)",
    "description": "A practical playbook to reduce load balancer costs: cut LB-hours, reduce LCU/NLCU drivers (connections/bytes/requests), and prevent incident traffic amplification with a measurable validation plan.",
    "canonicalPath": "/guides/aws-load-balancer-cost-optimization",
    "category": "AWS",
    "slug": "aws-load-balancer-cost-optimization",
    "topics": [
      "load-balancing",
      "requests"
    ]
  },
  {
    "title": "Load balancer costs: what to include beyond node spend",
    "description": "A practical guide to load balancer costs: fixed hourly charges, usage-based capacity units (LCU/NLCU), and the architecture patterns that quietly increase spend in Kubernetes and web stacks.",
    "canonicalPath": "/guides/aws-load-balancer-cost",
    "category": "AWS",
    "slug": "aws-load-balancer-cost",
    "topics": [
      "kubernetes",
      "load-balancing"
    ]
  },
  {
    "title": "Load balancer LCU/NLCU explained (for cost estimates)",
    "description": "A practical explanation of LCU/NLCU billing: what capacity unit-hours represent, which traffic patterns drive them, and how to reason about budgets before you have perfect metrics.",
    "canonicalPath": "/guides/aws-load-balancer-lcu-explained",
    "category": "AWS",
    "slug": "aws-load-balancer-lcu-explained",
    "topics": [
      "load-balancing",
      "metrics"
    ]
  },
  {
    "title": "NAT Gateway cost optimization (high-leverage fixes)",
    "description": "A practical playbook to reduce NAT Gateway spend: cut GB processed with private connectivity, remove recurring downloads, prevent retry storms, and validate savings with metrics/flow logs.",
    "canonicalPath": "/guides/aws-nat-gateway-cost-optimization",
    "category": "AWS",
    "slug": "aws-nat-gateway-cost-optimization",
    "topics": [
      "logging",
      "metrics",
      "requests"
    ]
  },
  {
    "title": "NAT gateway costs: why they spike and how to estimate them",
    "description": "NAT gateways can create surprising bills because costs scale with both time and traffic. Learn a practical way to estimate gateway-hours + GB processed, find the top traffic sources, and validate savings after fixes.",
    "canonicalPath": "/guides/aws-nat-gateway-cost",
    "category": "AWS",
    "slug": "aws-nat-gateway-cost",
    "topics": [
      "requests"
    ]
  },
  {
    "title": "NAT Gateway vs VPC endpoints cost: when PrivateLink wins",
    "description": "Compare NAT Gateway vs VPC endpoints (Interface/Gateway endpoints) cost: model gateway-hours + GB processed versus endpoint-hours + per-GB, estimate how much NAT traffic endpoints remove, and avoid transfer surprises.",
    "canonicalPath": "/guides/aws-nat-gateway-vs-vpc-endpoints-cost",
    "category": "AWS",
    "slug": "aws-nat-gateway-vs-vpc-endpoints-cost",
    "topics": [
      "egress",
      "requests"
    ]
  },
  {
    "title": "Parameter Store cost optimization (reduce API calls safely)",
    "description": "A high-leverage playbook to reduce SSM Parameter Store costs: cache parameters, reduce churn-driven fetches, and avoid per-request lookups. Includes validation steps and related tools.",
    "canonicalPath": "/guides/aws-ssm-parameter-store-cost-optimization",
    "category": "AWS",
    "slug": "aws-ssm-parameter-store-cost-optimization",
    "topics": [
      "requests"
    ]
  },
  {
    "title": "PrivateLink cost optimization: reduce endpoint-hours, GB processed, and operational sprawl",
    "description": "A practical PrivateLink optimization playbook: minimize endpoint-hours (endpoints × AZs × hours), reduce traffic volume safely, avoid cross-AZ transfer surprises, and prevent endpoint sprawl across environments.",
    "canonicalPath": "/guides/aws-privatelink-cost-optimization",
    "category": "AWS",
    "slug": "aws-privatelink-cost-optimization",
    "topics": [
      "egress",
      "storage"
    ]
  },
  {
    "title": "RDS backups and snapshots (how to estimate cost)",
    "description": "A practical approach to estimating RDS backup and snapshot storage: retention, growth, and the biggest planning mistakes.",
    "canonicalPath": "/guides/aws-rds-backups-and-snapshots",
    "category": "AWS",
    "slug": "aws-rds-backups-and-snapshots",
    "topics": [
      "backup",
      "database",
      "storage"
    ]
  },
  {
    "title": "RDS snapshot retention policy: cost model and safe defaults",
    "description": "How to choose an RDS snapshot retention policy without surprise costs: model retention vs churn, avoid redundant snapshots, and set long-term retention intentionally.",
    "canonicalPath": "/guides/aws-rds-snapshot-retention-policy-cost",
    "category": "AWS",
    "slug": "aws-rds-snapshot-retention-policy-cost",
    "topics": [
      "backup",
      "database"
    ]
  },
  {
    "title": "RDS vs Aurora cost: what to compare (compute, storage, I/O, and retention)",
    "description": "A practical RDS vs Aurora cost comparison checklist. Compare unit economics, scaling model, storage growth, backups/retention, and the workload patterns that change the answer.",
    "canonicalPath": "/guides/aws-rds-vs-aurora-cost",
    "category": "AWS",
    "slug": "aws-rds-vs-aurora-cost",
    "topics": [
      "backup",
      "compute",
      "database",
      "storage"
    ]
  },
  {
    "title": "Reserved vs on-demand: how to choose commitments using break-even analysis",
    "description": "A practical guide to choosing commitments: use break-even utilization and sensitivity analysis to decide when reserved pricing beats on-demand.",
    "canonicalPath": "/guides/aws-reserved-vs-on-demand",
    "category": "AWS",
    "slug": "aws-reserved-vs-on-demand",
    "topics": []
  },
  {
    "title": "Route 53 cost optimization (reduce query volume and zone sprawl)",
    "description": "A practical playbook to reduce Route 53 costs: reduce DNS query volume, fix low TTL defaults, and avoid hosted zone sprawl across environments. Includes validation steps and related tools.",
    "canonicalPath": "/guides/aws-route-53-cost-optimization",
    "category": "AWS",
    "slug": "aws-route-53-cost-optimization",
    "topics": [
      "storage"
    ]
  },
  {
    "title": "Route 53 pricing: what to model (zones, queries, health checks)",
    "description": "A practical Route 53 pricing checklist: hosted zones, DNS query volume, health checks, and the patterns that create surprise query bills.",
    "canonicalPath": "/guides/aws-route-53-pricing",
    "category": "AWS",
    "slug": "aws-route-53-pricing",
    "topics": []
  },
  {
    "title": "S3 data transfer costs: egress, cross-region access, and common surprises",
    "description": "A practical guide to S3 data transfer costs: what counts as egress, how cross-region access shows up on bills, and how to estimate GB/month from your traffic patterns.",
    "canonicalPath": "/guides/aws-s3-data-transfer",
    "category": "AWS",
    "slug": "aws-s3-data-transfer",
    "topics": [
      "egress",
      "storage"
    ]
  },
  {
    "title": "S3 Glacier and Deep Archive pricing (storage, retrieval, minimum duration)",
    "description": "A practical pricing checklist for S3 Glacier/Deep Archive: storage GB-month, retrieval volume and requests, and minimum storage duration/early deletion fees.",
    "canonicalPath": "/guides/aws-s3-glacier-pricing",
    "category": "AWS",
    "slug": "aws-s3-glacier-pricing",
    "topics": [
      "requests",
      "storage"
    ]
  },
  {
    "title": "S3 pricing: a practical model for storage, requests, egress, and replication",
    "description": "A practical S3 pricing guide: what to include (GB-month, requests, egress, replication) and how to estimate the key inputs without copying price tables.",
    "canonicalPath": "/guides/aws-s3-pricing",
    "category": "AWS",
    "slug": "aws-s3-pricing",
    "topics": [
      "egress",
      "requests",
      "storage"
    ]
  },
  {
    "title": "S3 replication pricing: estimate replicated GB/month and total impact",
    "description": "A practical guide to S3 replication pricing: replication volume (changed data), extra destination storage, transfer-like charges, and when CRR vs SRR changes the bill.",
    "canonicalPath": "/guides/aws-s3-replication-pricing",
    "category": "AWS",
    "slug": "aws-s3-replication-pricing",
    "topics": [
      "egress",
      "storage"
    ]
  },
  {
    "title": "S3 request costs: when GET/PUT/LIST becomes meaningful",
    "description": "S3 request costs are often tiny, but they can matter for workloads with many small objects or high metadata churn. Learn how to estimate request fees and when to care.",
    "canonicalPath": "/guides/aws-s3-request-costs",
    "category": "AWS",
    "slug": "aws-s3-request-costs",
    "topics": [
      "requests",
      "storage"
    ]
  },
  {
    "title": "S3 storage classes: how they change cost (and when archive fees matter)",
    "description": "A practical guide to S3-like storage classes: why cheaper storage can come with retrieval/transition tradeoffs, and how to model cost with simple assumptions.",
    "canonicalPath": "/guides/aws-s3-storage-classes",
    "category": "AWS",
    "slug": "aws-s3-storage-classes",
    "topics": [
      "storage"
    ]
  },
  {
    "title": "Secrets Manager cost optimization (reduce API calls safely)",
    "description": "A high-leverage playbook to reduce Secrets Manager costs: cache secrets, avoid per-request lookups, and reduce churn-driven fetches. Includes validation steps and related tools.",
    "canonicalPath": "/guides/aws-secrets-manager-cost-optimization",
    "category": "AWS",
    "slug": "aws-secrets-manager-cost-optimization",
    "topics": [
      "requests",
      "storage"
    ]
  },
  {
    "title": "Secrets Manager pricing: what to model (secrets + API calls)",
    "description": "A practical Secrets Manager pricing checklist: secret-month baseline plus API request charges, the runtime patterns that create request-driven spikes, and how to validate and optimize safely.",
    "canonicalPath": "/guides/aws-secrets-manager-pricing",
    "category": "AWS",
    "slug": "aws-secrets-manager-pricing",
    "topics": [
      "requests",
      "storage"
    ]
  },
  {
    "title": "SES cost optimization (reduce volume, retries, and payload)",
    "description": "A practical playbook to reduce AWS SES costs: prevent duplicate sends, control retries and alert storms, reduce non-prod waste, and keep payloads small when they matter — with validation steps to protect deliverability.",
    "canonicalPath": "/guides/aws-ses-cost-optimization",
    "category": "AWS",
    "slug": "aws-ses-cost-optimization",
    "topics": []
  },
  {
    "title": "SES pricing: what to model (send volume + payload size)",
    "description": "A practical AWS SES pricing checklist: emails sent, optional payload/attachment size assumptions, and the operational patterns (retries, alert storms, duplicates) that create surprise spend.",
    "canonicalPath": "/guides/aws-ses-pricing",
    "category": "AWS",
    "slug": "aws-ses-pricing",
    "topics": []
  },
  {
    "title": "SNS cost optimization (reduce deliveries and retries)",
    "description": "A high-leverage playbook to reduce SNS costs: reduce fan-out (deliveries), reduce delivery retries by fixing endpoints, and prevent alert storms with dedupe and rate limits — with a validation plan.",
    "canonicalPath": "/guides/aws-sns-cost-optimization",
    "category": "AWS",
    "slug": "aws-sns-cost-optimization",
    "topics": [
      "messaging"
    ]
  },
  {
    "title": "SNS pricing: what to model (publishes, deliveries, fan-out)",
    "description": "A practical SNS pricing checklist: publish requests, delivery requests by protocol mix, fan-out after filter policies, and the retry/alert-storm patterns that create surprise delivery volume.",
    "canonicalPath": "/guides/aws-sns-pricing",
    "category": "AWS",
    "slug": "aws-sns-pricing",
    "topics": [
      "messaging",
      "requests"
    ]
  },
  {
    "title": "SQS vs SNS cost: how to compare messaging unit economics",
    "description": "Compare SQS vs SNS cost with a practical checklist: request types, retries, fan-out, payload transfer, and the usage patterns that decide the bill.",
    "canonicalPath": "/guides/aws-sqs-vs-sns-cost",
    "category": "AWS",
    "slug": "aws-sqs-vs-sns-cost",
    "topics": [
      "egress",
      "messaging",
      "requests"
    ]
  },
  {
    "title": "SSM Parameter Store pricing: what to model (advanced params + API calls)",
    "description": "A practical Parameter Store pricing checklist: standard vs advanced parameters, API call volume, and the common patterns that create request-driven cost spikes.",
    "canonicalPath": "/guides/aws-ssm-parameter-store-pricing",
    "category": "AWS",
    "slug": "aws-ssm-parameter-store-pricing",
    "topics": [
      "requests"
    ]
  },
  {
    "title": "VPC data transfer: how to estimate cross-zone, cross-region, and egress costs",
    "description": "A practical guide to VPC data transfer: where transfer happens in real architectures, how to estimate GB/month, and how to avoid surprises.",
    "canonicalPath": "/guides/aws-vpc-data-transfer",
    "category": "AWS",
    "slug": "aws-vpc-data-transfer",
    "topics": [
      "egress"
    ]
  },
  {
    "title": "VPC endpoints cost optimization: reduce endpoint-hours and avoid transfer pitfalls",
    "description": "A practical playbook to reduce VPC interface endpoint costs: consolidate endpoints, right-size AZ coverage, reduce endpoint GB processed, and avoid cross-AZ transfer pitfalls.",
    "canonicalPath": "/guides/aws-vpc-endpoints-cost-optimization",
    "category": "AWS",
    "slug": "aws-vpc-endpoints-cost-optimization",
    "topics": [
      "egress"
    ]
  },
  {
    "title": "VPC endpoints pricing: what to model (interface vs gateway endpoints)",
    "description": "A practical VPC endpoints pricing checklist: interface endpoint hours, per-GB processing, gateway endpoint differences, and the transfer pitfalls that cause surprises.",
    "canonicalPath": "/guides/aws-vpc-endpoints-pricing",
    "category": "AWS",
    "slug": "aws-vpc-endpoints-pricing",
    "topics": [
      "egress",
      "requests"
    ]
  },
  {
    "title": "WAF cost optimization (reduce requests + rule sprawl)",
    "description": "A practical playbook to reduce WAF spend: cut evaluated requests, keep rule count tight, and avoid downstream logging waste.",
    "canonicalPath": "/guides/aws-waf-cost-optimization",
    "category": "AWS",
    "slug": "aws-waf-cost-optimization",
    "topics": [
      "logging",
      "requests",
      "security"
    ]
  },
  {
    "title": "WAF cost spikes during attacks: how to budget request surges",
    "description": "A practical guide to WAF cost spikes during attacks: why request-based charges jump, how to model surge traffic, and how to reduce evaluated requests and logging volume safely.",
    "canonicalPath": "/guides/aws-waf-cost-spikes-during-attacks",
    "category": "AWS",
    "slug": "aws-waf-cost-spikes-during-attacks",
    "topics": [
      "logging",
      "requests",
      "security"
    ]
  },
  {
    "title": "Azure API Management pricing: model requests, transfer, and log volume",
    "description": "A practical API Management estimate: request volume, response transfer, and logs/observability. Includes a checklist to validate retries, payload size, and usage tiers.",
    "canonicalPath": "/guides/azure-api-management-pricing",
    "category": "Azure",
    "slug": "azure-api-management-pricing",
    "topics": [
      "egress",
      "logging",
      "requests"
    ]
  },
  {
    "title": "Azure Application Gateway pricing: how to model L7 load balancer costs",
    "description": "Model Application Gateway costs using measurable drivers: hours, request volume, traffic processed, WAF, and logs - plus a validation checklist.",
    "canonicalPath": "/guides/azure-application-gateway-pricing",
    "category": "Azure",
    "slug": "azure-application-gateway-pricing",
    "topics": [
      "load-balancing",
      "logging",
      "requests",
      "security"
    ]
  },
  {
    "title": "Azure Application Insights pricing: ingestion volume, sampling, and retention",
    "description": "A practical Application Insights estimate: telemetry volume (GB), sampling, retention, and query scans. Includes validation steps to prevent ingest spikes during incidents.",
    "canonicalPath": "/guides/azure-application-insights-pricing",
    "category": "Azure",
    "slug": "azure-application-insights-pricing",
    "topics": [
      "backup",
      "metrics"
    ]
  },
  {
    "title": "Azure bandwidth and egress costs: how to estimate outbound data transfer",
    "description": "A practical method to estimate outbound bandwidth costs: split by destination (internet, cross-region, CDN origin), validate units, and avoid double-counting.",
    "canonicalPath": "/guides/azure-bandwidth-egress-costs",
    "category": "Azure",
    "slug": "azure-bandwidth-egress-costs",
    "topics": [
      "cdn",
      "egress"
    ]
  },
  {
    "title": "Azure Blob Storage pricing: a practical cost model",
    "description": "Model Blob Storage cost without copying price tables: GB-month, operations, redundancy/replication, retrieval, and egress.",
    "canonicalPath": "/guides/azure-blob-storage-pricing",
    "category": "Azure",
    "slug": "azure-blob-storage-pricing",
    "topics": [
      "egress",
      "storage"
    ]
  },
  {
    "title": "Azure CDN pricing: estimate bandwidth, requests, and cache fill",
    "description": "A practical Azure CDN estimate: edge bandwidth, request volume, and origin egress (cache fill). Includes validation steps for hit rate, purge behavior, and big endpoints.",
    "canonicalPath": "/guides/azure-cdn-pricing",
    "category": "Azure",
    "slug": "azure-cdn-pricing",
    "topics": [
      "cdn",
      "egress",
      "requests"
    ]
  },
  {
    "title": "Azure Container Registry (ACR) pricing: storage + pulls + egress",
    "description": "A practical ACR pricing model: image storage (GB-month), pull volume, and data transfer. Includes a workflow to estimate GB-month from retention and validate layer sharing.",
    "canonicalPath": "/guides/azure-container-registry-pricing",
    "category": "Azure",
    "slug": "azure-container-registry-pricing",
    "topics": [
      "backup",
      "compute",
      "egress",
      "storage"
    ]
  },
  {
    "title": "Azure Cosmos DB pricing: a practical estimate (RU/s, storage, and egress)",
    "description": "A driver-based Cosmos DB estimate: RU/s capacity, stored GB, and data transfer. Includes a workflow to validate RU drivers and avoid underestimating burst, hot partitions, and retries.",
    "canonicalPath": "/guides/azure-cosmos-db-pricing",
    "category": "Azure",
    "slug": "azure-cosmos-db-pricing",
    "topics": [
      "egress",
      "storage"
    ]
  },
  {
    "title": "Azure Event Hubs pricing: estimate throughput, events, and retention",
    "description": "A practical Event Hubs estimate: ingestion throughput, event volume, retention, and downstream egress. Includes validation steps for burst traffic, consumer lag, and replay/backfill multipliers.",
    "canonicalPath": "/guides/azure-event-hubs-pricing",
    "category": "Azure",
    "slug": "azure-event-hubs-pricing",
    "topics": [
      "backup",
      "egress",
      "messaging"
    ]
  },
  {
    "title": "Azure Front Door pricing: model requests, bandwidth, and origin traffic",
    "description": "A practical Azure Front Door cost model: edge bandwidth, request volume, logging, and origin traffic (cache fill). Includes a checklist to validate hit rate and avoid double-counting egress.",
    "canonicalPath": "/guides/azure-front-door-pricing",
    "category": "Azure",
    "slug": "azure-front-door-pricing",
    "topics": [
      "cdn",
      "egress",
      "logging",
      "requests"
    ]
  },
  {
    "title": "Azure Functions pricing: what to include in a realistic estimate",
    "description": "A practical Azure Functions cost model: invocations, duration/memory, networking, and log volume - plus a validation checklist to catch retries, cold starts, and chatty dependencies.",
    "canonicalPath": "/guides/azure-functions-pricing",
    "category": "Azure",
    "slug": "azure-functions-pricing",
    "topics": [
      "logging",
      "serverless"
    ]
  },
  {
    "title": "Azure Key Vault pricing: estimate operations, keys/secrets, and request spikes",
    "description": "A practical Key Vault cost model: baseline objects (keys/secrets/certs) plus operation volume. Includes a workflow to map traffic to Key Vault calls and validate caching, retries, and hot-path mistakes.",
    "canonicalPath": "/guides/azure-key-vault-pricing",
    "category": "Azure",
    "slug": "azure-key-vault-pricing",
    "topics": [
      "requests",
      "security",
      "storage"
    ]
  },
  {
    "title": "Azure Kubernetes Service (AKS) pricing: what to include",
    "description": "AKS cost is more than node VMs: include node pools, networking/egress, storage, and observability. Use this checklist-style model to estimate safely.",
    "canonicalPath": "/guides/azure-aks-pricing",
    "category": "Azure",
    "slug": "azure-aks-pricing",
    "topics": [
      "compute",
      "egress",
      "kubernetes",
      "storage"
    ]
  },
  {
    "title": "Azure Load Balancer pricing: L4 traffic and data processing model",
    "description": "A practical cost model for Azure Load Balancer: hours, data processed, and egress boundaries. Includes a workflow to estimate GB processed from RPS and payload size, plus a validation checklist for peaks and retries.",
    "canonicalPath": "/guides/azure-load-balancer-pricing",
    "category": "Azure",
    "slug": "azure-load-balancer-pricing",
    "topics": [
      "egress",
      "kubernetes",
      "load-balancing"
    ]
  },
  {
    "title": "Azure Log Analytics pricing: ingestion, retention, and query costs",
    "description": "A practical model for Log Analytics-style costs: GB ingested, retention storage, and query/scan behavior. Includes a method to estimate log GB from event rate and payload size, plus a validation checklist for high-volume sources.",
    "canonicalPath": "/guides/azure-log-analytics-pricing",
    "category": "Azure",
    "slug": "azure-log-analytics-pricing",
    "topics": [
      "backup",
      "logging",
      "storage"
    ]
  },
  {
    "title": "Azure Monitor metrics pricing: estimate custom metrics, retention, and API calls",
    "description": "A practical metrics cost model: time series count, sample rate, retention, and dashboard/alert query behavior. Includes validation steps to avoid high-cardinality mistakes.",
    "canonicalPath": "/guides/azure-monitor-metrics-pricing",
    "category": "Azure",
    "slug": "azure-monitor-metrics-pricing",
    "topics": [
      "backup",
      "metrics",
      "requests"
    ]
  },
  {
    "title": "Azure NAT Gateway cost: model hours, GB processed, and the real spike drivers",
    "description": "A practical Azure NAT Gateway estimate: hourly baseline, GB processed, and the common multipliers (retries, image pulls, dependency storms). Includes a validation checklist and cost-reduction levers.",
    "canonicalPath": "/guides/azure-nat-gateway-cost",
    "category": "Azure",
    "slug": "azure-nat-gateway-cost",
    "topics": [
      "requests"
    ]
  },
  {
    "title": "Azure Private Link costs: model endpoint-hours, data processed, and trade-offs vs NAT",
    "description": "A practical Private Link estimate: endpoint-hours baseline plus data processed (GB). Includes a workflow to count endpoints, model traffic through them, and validate DNS/routing so you don't pay for both private and NAT paths.",
    "canonicalPath": "/guides/azure-private-link-costs",
    "category": "Azure",
    "slug": "azure-private-link-costs",
    "topics": []
  },
  {
    "title": "Azure Service Bus pricing: estimate messaging cost from operations, retries, and payload",
    "description": "A practical Service Bus estimate: message volume, deliveries/retries, fan-out, and payload transfer. Includes a workflow to model baseline vs peak and validate the real multipliers (timeouts, DLQ replays, and subscription expansion).",
    "canonicalPath": "/guides/azure-service-bus-pricing",
    "category": "Azure",
    "slug": "azure-service-bus-pricing",
    "topics": [
      "egress",
      "messaging"
    ]
  },
  {
    "title": "Azure SQL Database pricing: a practical estimate (compute, storage, backups, transfer)",
    "description": "Model Azure SQL Database cost without memorizing price tables: compute baseline (vCore/DTU), storage GB-month + growth, backup retention, and network transfer. Includes a validation checklist and common sizing traps.",
    "canonicalPath": "/guides/azure-sql-database-pricing",
    "category": "Azure",
    "slug": "azure-sql-database-pricing",
    "topics": [
      "backup",
      "compute",
      "database",
      "egress",
      "storage"
    ]
  },
  {
    "title": "CDN Costs Explained: bandwidth, requests, and origin egress",
    "description": "A practical CDN cost breakdown: what you pay for bandwidth ($/GB), request fees ($ per 10k/1M), cache fill, and origin egress. Includes estimation steps and common pitfalls.",
    "canonicalPath": "/guides/cdn-costs",
    "category": "CDN",
    "slug": "cdn-costs",
    "topics": [
      "cdn",
      "egress",
      "requests"
    ]
  },
  {
    "title": "CDN request pricing: estimate $ per 10k / 1M requests (and when it dominates)",
    "description": "Some CDNs charge request fees in addition to bandwidth. Learn what counts as a billable request, how to estimate requests/month from RPS or analytics, and how to model per-10k vs per-1M pricing without unit mistakes.",
    "canonicalPath": "/guides/cdn-request-pricing",
    "category": "CDN",
    "slug": "cdn-request-pricing",
    "topics": [
      "cdn",
      "egress",
      "requests"
    ]
  },
  {
    "title": "CloudFront vs Cloudflare CDN cost: compare the right line items (bandwidth, requests, origin egress)",
    "description": "A practical comparison checklist for CloudFront vs Cloudflare pricing. Compare bandwidth ($/GB), request fees, region mix, origin egress (cache fill), and add-ons like WAF, logs, and edge compute. Includes a modeling template and validation steps.",
    "canonicalPath": "/guides/cloudfront-vs-cloudflare-cdn-cost",
    "category": "CDN",
    "slug": "cloudfront-vs-cloudflare-cdn-cost",
    "topics": [
      "cdn",
      "compute",
      "egress",
      "logging",
      "requests",
      "security"
    ]
  },
  {
    "title": "How to estimate CDN bandwidth (GB/month): analytics, RPS, or Mbps",
    "description": "A practical guide to estimating CDN bandwidth per month. Includes methods from CDN analytics, from RPS × response size, and from throughput (Mbps), plus unit pitfalls (bits vs bytes, GB vs GiB) and a validation checklist.",
    "canonicalPath": "/guides/estimate-cdn-bandwidth-gb-per-month",
    "category": "CDN",
    "slug": "estimate-cdn-bandwidth-gb-per-month",
    "topics": [
      "cdn",
      "egress"
    ]
  },
  {
    "title": "Origin egress vs CDN bandwidth: what's the difference?",
    "description": "CDN bills often have two related but different bandwidth concepts: origin egress (from your origin) and CDN bandwidth (to end users). Learn how to model both without double-counting.",
    "canonicalPath": "/guides/origin-egress-vs-cdn-bandwidth",
    "category": "CDN",
    "slug": "origin-egress-vs-cdn-bandwidth",
    "topics": [
      "cdn",
      "egress"
    ]
  },
  {
    "title": "Artifact Registry pricing (GCP): storage + downloads + egress (practical estimate)",
    "description": "A practical Artifact Registry cost model: stored GB-month baseline, download volume from CI/CD and cluster churn, and outbound transfer. Includes a workflow to estimate GB-month from retention and validate layer sharing and peak pull storms.",
    "canonicalPath": "/guides/gcp-artifact-registry-pricing",
    "category": "GCP",
    "slug": "gcp-artifact-registry-pricing",
    "topics": [
      "backup",
      "egress",
      "storage"
    ]
  },
  {
    "title": "BigQuery cost estimation: storage, bytes scanned, and the dashboard trap",
    "description": "Estimate BigQuery-style analytics costs with measurable drivers: stored data (GB-month), bytes scanned (per query), and streaming/exports. Includes a workflow to model baseline vs peak and validate partition pruning and dashboard refresh behavior.",
    "canonicalPath": "/guides/gcp-bigquery-cost-estimation",
    "category": "GCP",
    "slug": "gcp-bigquery-cost-estimation",
    "topics": [
      "storage"
    ]
  },
  {
    "title": "Bigtable cost estimation: nodes, storage growth, and transfer (practical model)",
    "description": "A driver-based Bigtable estimate: provisioned capacity (node-hours), stored GB-month + growth, and network transfer. Includes validation steps for hotspots, compactions, and peak throughput that force over-provisioning.",
    "canonicalPath": "/guides/gcp-bigtable-cost-estimation",
    "category": "GCP",
    "slug": "gcp-bigtable-cost-estimation",
    "topics": [
      "database",
      "egress",
      "storage"
    ]
  },
  {
    "title": "Cloud Armor pricing (GCP): model baseline traffic, attack spikes, and logging",
    "description": "A practical Cloud Armor estimate: baseline request volume plus an attack scenario (peak RPS × duration). Includes validation steps for spikes, rule footprint, and the secondary cost driver most teams miss: logs and analytics during incidents.",
    "canonicalPath": "/guides/gcp-cloud-armor-pricing",
    "category": "GCP",
    "slug": "gcp-cloud-armor-pricing",
    "topics": [
      "logging",
      "requests",
      "security"
    ]
  },
  {
    "title": "Cloud CDN pricing (GCP): bandwidth, requests, and origin egress (cache fill)",
    "description": "A practical Cloud CDN cost model: edge bandwidth, request volume, and origin egress (cache fill). Includes validation steps for hit rate by path, heavy-tail endpoints, and purge/deploy events that reduce hit rate.",
    "canonicalPath": "/guides/gcp-cloud-cdn-pricing",
    "category": "GCP",
    "slug": "gcp-cloud-cdn-pricing",
    "topics": [
      "cdn",
      "egress",
      "requests"
    ]
  },
  {
    "title": "Cloud Functions pricing (GCP): invocations, duration, egress, and log volume",
    "description": "A practical Cloud Functions cost model: invocations, execution time, outbound transfer, and logs. Includes a workflow to estimate baseline + peak and validate retries, cold starts, and log bytes per invocation.",
    "canonicalPath": "/guides/gcp-cloud-functions-pricing",
    "category": "GCP",
    "slug": "gcp-cloud-functions-pricing",
    "topics": [
      "egress",
      "logging",
      "serverless"
    ]
  },
  {
    "title": "Cloud Logging pricing (GCP): ingestion, retention, and query scans",
    "description": "A practical model for Cloud Logging costs: GB ingested, retention storage (GB-month), and query/scan behavior. Includes a fast method to estimate GB/day from events/sec × bytes/event and a checklist to find dominant sources.",
    "canonicalPath": "/guides/gcp-cloud-logging-pricing",
    "category": "GCP",
    "slug": "gcp-cloud-logging-pricing",
    "topics": [
      "backup",
      "logging",
      "storage"
    ]
  },
  {
    "title": "Cloud Monitoring metrics pricing (GCP): time series, sample rate, and retention",
    "description": "A practical metrics cost model: time series count (cardinality), sample rate, retention, and dashboard/alert query behavior. Includes validation steps to prevent high-cardinality explosions and excessive refresh patterns.",
    "canonicalPath": "/guides/gcp-cloud-monitoring-metrics-pricing",
    "category": "GCP",
    "slug": "gcp-cloud-monitoring-metrics-pricing",
    "topics": [
      "backup",
      "metrics"
    ]
  },
  {
    "title": "Cloud NAT cost (GCP): why it spikes and how to model outbound traffic",
    "description": "A practical Cloud NAT estimate: baseline configuration + outbound GB processed through NAT, with a peak scenario for retries, node churn, and dependency storms. Includes a validation checklist and cost-reduction levers.",
    "canonicalPath": "/guides/gcp-cloud-nat-cost",
    "category": "GCP",
    "slug": "gcp-cloud-nat-cost",
    "topics": []
  },
  {
    "title": "Cloud Run pricing (GCP): requests, CPU/memory time, and egress (practical model)",
    "description": "Estimate Cloud Run-style serverless container cost using measurable drivers: request volume, duration, concurrency, outbound transfer, and logs. Includes a validation checklist for retries, cold starts, and heavy-tail response sizes.",
    "canonicalPath": "/guides/gcp-cloud-run-pricing",
    "category": "GCP",
    "slug": "gcp-cloud-run-pricing",
    "topics": [
      "compute",
      "egress",
      "logging",
      "requests",
      "serverless"
    ]
  },
  {
    "title": "Cloud Spanner cost estimation: capacity, storage, backups, and multi-region traffic",
    "description": "Estimate Spanner cost using measurable drivers: provisioned capacity (baseline + peak), stored GB-month (data + indexes), backups/retention, and multi-region/network patterns. Includes a worked template, common pitfalls, and validation steps.",
    "canonicalPath": "/guides/gcp-cloud-spanner-cost-estimation",
    "category": "GCP",
    "slug": "gcp-cloud-spanner-cost-estimation",
    "topics": [
      "backup",
      "database",
      "storage"
    ]
  },
  {
    "title": "Cloud SQL pricing: instance-hours, storage, backups, and network (practical estimate)",
    "description": "A driver-based Cloud SQL estimate: instance-hours (HA + replicas), storage GB-month, backups/retention, and data transfer. Includes a worked template, common pitfalls, and validation steps for peak sizing and growth.",
    "canonicalPath": "/guides/gcp-cloud-sql-pricing",
    "category": "GCP",
    "slug": "gcp-cloud-sql-pricing",
    "topics": [
      "backup",
      "compute",
      "database",
      "egress",
      "storage"
    ]
  },
  {
    "title": "Dataflow pricing: worker hours, backlog catch-up, and observability (practical model)",
    "description": "Estimate Dataflow cost using measurable drivers: worker compute-hours, backlog catch-up scenarios (replays/backfills), data processed, and logs/metrics. Includes a worked template, pitfalls, and validation steps for autoscaling and replay patterns.",
    "canonicalPath": "/guides/gcp-dataflow-pricing",
    "category": "GCP",
    "slug": "gcp-dataflow-pricing",
    "topics": [
      "compute",
      "logging",
      "metrics"
    ]
  },
  {
    "title": "GCP load balancing pricing: hours, requests, traffic processed, and egress",
    "description": "A driver-based approach to load balancer cost: hours, request volume, traffic processed, and (separately) outbound egress. Includes a worked estimate template, pitfalls, and a workflow to estimate GB from RPS and response size.",
    "canonicalPath": "/guides/gcp-load-balancing-pricing",
    "category": "GCP",
    "slug": "gcp-load-balancing-pricing",
    "topics": [
      "egress",
      "load-balancing",
      "requests"
    ]
  },
  {
    "title": "GCP VPC egress costs: estimate outbound transfer by destination (practical workflow)",
    "description": "A practical method to estimate GCP outbound transfer: split by destination (internet, cross-region, inter-zone, CDN origin), convert usage to GB/month, and validate boundaries. Includes a worked template, pitfalls, and optimization levers.",
    "canonicalPath": "/guides/gcp-vpc-egress-costs",
    "category": "GCP",
    "slug": "gcp-vpc-egress-costs",
    "topics": [
      "cdn",
      "egress"
    ]
  },
  {
    "title": "Google Cloud Storage pricing: storage class, operations, retrieval, replication, and egress",
    "description": "Model Cloud Storage cost without copying price tables: storage GB-month by class, operations (GET/PUT/LIST), retrieval and minimum storage duration rules, replication patterns, and outbound transfer. Includes a worked template, pitfalls, and validation checklist.",
    "canonicalPath": "/guides/gcp-cloud-storage-pricing",
    "category": "GCP",
    "slug": "gcp-cloud-storage-pricing",
    "topics": [
      "egress",
      "storage"
    ]
  },
  {
    "title": "Google Kubernetes Engine (GKE) pricing: nodes, networking, storage, and observability",
    "description": "GKE cost is not just nodes: include node pools, autoscaling, requests/limits (bin packing), load balancing/egress, storage, and logs/metrics. Includes a worked estimate template, pitfalls, and validation steps to keep clusters right-sized.",
    "canonicalPath": "/guides/gcp-gke-pricing",
    "category": "GCP",
    "slug": "gcp-gke-pricing",
    "topics": [
      "egress",
      "kubernetes",
      "logging",
      "metrics",
      "requests",
      "storage"
    ]
  },
  {
    "title": "Inter-zone transfer costs on GCP: identify flows, estimate GB/month, and reduce churn",
    "description": "A practical checklist to estimate cross-zone data transfer: load balancers, multi-zone clusters, east-west chatter, and storage/database access patterns. Includes a worked template, validation steps, and control levers.",
    "canonicalPath": "/guides/gcp-inter-zone-transfer-costs",
    "category": "GCP",
    "slug": "gcp-inter-zone-transfer-costs",
    "topics": [
      "database",
      "egress",
      "load-balancing",
      "storage"
    ]
  },
  {
    "title": "Private Service Connect costs: endpoint-hours and data processed (practical model)",
    "description": "A practical private connectivity estimate: endpoint-hours plus data processed (GB). Includes a worked template, pitfalls, and validation steps to compare PSC vs NAT/internet egress and avoid paying for both paths.",
    "canonicalPath": "/guides/gcp-private-service-connect-costs",
    "category": "GCP",
    "slug": "gcp-private-service-connect-costs",
    "topics": [
      "egress"
    ]
  },
  {
    "title": "Pub/Sub pricing: deliveries, retries, fan-out, and payload transfer (practical estimate)",
    "description": "A practical Pub/Sub estimate: publish volume, fan-out (subscriptions), delivery attempts (retries), retention/replay scenarios, and payload transfer. Includes a worked template, pitfalls, and validation steps.",
    "canonicalPath": "/guides/gcp-pubsub-pricing",
    "category": "GCP",
    "slug": "gcp-pubsub-pricing",
    "topics": [
      "backup",
      "egress",
      "messaging"
    ]
  },
  {
    "title": "Backup and snapshot costs explained: retention, growth, and transfer",
    "description": "A practical backup cost model: snapshot frequency and retention, stored GB-month growth, cross-region copies, and the hidden transfer charges that can surprise bills.",
    "canonicalPath": "/guides/backups-and-snapshots-costs",
    "category": "General",
    "slug": "backups-and-snapshots-costs",
    "topics": [
      "backup",
      "egress"
    ]
  },
  {
    "title": "Cloud cost estimation checklist: build a model Google (and finance) will trust",
    "description": "A practical checklist to estimate cloud cost without missing major line items: requests, compute, storage, logs/metrics, and network transfer. Includes a worksheet template, validation steps, and the most common double-counting traps.",
    "canonicalPath": "/guides/cloud-cost-estimation-checklist",
    "category": "General",
    "slug": "cloud-cost-estimation-checklist",
    "topics": [
      "compute",
      "egress",
      "logging",
      "metrics",
      "requests",
      "storage"
    ]
  },
  {
    "title": "Compute costs explained: instance-hours, utilization, and hidden drivers",
    "description": "A practical compute cost model: instance-hours (or vCPU/GB-hours), utilization and idle waste, plus the hidden drivers that often dominate totals (egress, load balancers, and logs).",
    "canonicalPath": "/guides/compute-costs",
    "category": "General",
    "slug": "compute-costs",
    "topics": [
      "compute",
      "egress",
      "load-balancing",
      "logging"
    ]
  },
  {
    "title": "Database costs explained: compute, storage growth, backups, and network",
    "description": "A practical framework to estimate managed database bills: baseline compute, storage GB-month growth, backups/snapshots, and the network patterns that cause surprises.",
    "canonicalPath": "/guides/database-costs",
    "category": "General",
    "slug": "database-costs",
    "topics": [
      "backup",
      "compute",
      "database",
      "storage"
    ]
  },
  {
    "title": "How to estimate replication GB/month from write volume",
    "description": "Replication cost is driven by changed data, not total stored GB. Learn how to estimate replicated GB/month from write throughput and change rates for S3-like storage.",
    "canonicalPath": "/guides/estimate-replication-gb-per-month-from-writes",
    "category": "General",
    "slug": "estimate-replication-gb-per-month-from-writes",
    "topics": [
      "storage"
    ]
  },
  {
    "title": "Load balancing costs explained: hours, requests, and traffic processed",
    "description": "A practical load balancer cost model: hourly baseline, request-based pricing, GB processed, WAF add-ons, and the patterns that create cross-zone traffic surprises.",
    "canonicalPath": "/guides/load-balancing-costs",
    "category": "General",
    "slug": "load-balancing-costs",
    "topics": [
      "load-balancing",
      "requests",
      "security"
    ]
  },
  {
    "title": "Messaging costs explained: requests, deliveries, retries, and payload size",
    "description": "A practical framework to estimate queue and pub/sub bills: request-based pricing, deliveries/retries, fan-out, and payload transfer (the hidden multiplier).",
    "canonicalPath": "/guides/messaging-costs",
    "category": "General",
    "slug": "messaging-costs",
    "topics": [
      "egress",
      "messaging",
      "requests"
    ]
  },
  {
    "title": "Metrics and monitoring costs explained: series, cardinality, and retention",
    "description": "A practical framework to estimate metrics bills: number of unique time series (cardinality), retention, dashboards/alerts, and the fastest levers to reduce cost safely.",
    "canonicalPath": "/guides/metrics-costs",
    "category": "General",
    "slug": "metrics-costs",
    "topics": [
      "backup",
      "database",
      "metrics"
    ]
  },
  {
    "title": "Networking costs explained: egress, transfer boundaries, NAT, and private connectivity",
    "description": "A practical networking cost model: internet egress, cross-zone/region transfer, NAT/private endpoints, and how to validate boundaries to avoid double counting.",
    "canonicalPath": "/guides/networking-costs",
    "category": "General",
    "slug": "networking-costs",
    "topics": [
      "egress"
    ]
  },
  {
    "title": "Observability costs explained: logs, metrics, traces, and query behavior",
    "description": "A practical observability cost model: log ingestion + retention, metrics series cardinality, traces volume, and the query patterns that create scan/search charges.",
    "canonicalPath": "/guides/observability-costs",
    "category": "General",
    "slug": "observability-costs",
    "topics": [
      "backup",
      "logging",
      "metrics"
    ]
  },
  {
    "title": "Request-based pricing explained (APIs, CDN, and messaging)",
    "description": "A practical guide to request-based pricing: how to estimate requests/month, translate RPS to monthly volume, and avoid unit mistakes (per 10k vs per 1M). Includes validation steps.",
    "canonicalPath": "/guides/request-based-pricing",
    "category": "General",
    "slug": "request-based-pricing",
    "topics": [
      "cdn",
      "requests"
    ]
  },
  {
    "title": "Security costs explained: WAF, keys/secrets, and request-driven spikes",
    "description": "A practical security cost model: WAF request-based pricing, key management (KMS/Key Vault) operations, secrets access patterns, and how bot traffic or high-frequency crypto can surprise budgets.",
    "canonicalPath": "/guides/security-costs",
    "category": "General",
    "slug": "security-costs",
    "topics": [
      "requests",
      "security",
      "storage"
    ]
  },
  {
    "title": "Serverless costs explained: invocations, duration, requests, and downstream spend",
    "description": "A practical serverless cost model: invocations and duration (compute time), request-based add-ons, networking/egress, and the log/metric drivers that often dominate totals.",
    "canonicalPath": "/guides/serverless-costs",
    "category": "General",
    "slug": "serverless-costs",
    "topics": [
      "compute",
      "egress",
      "logging",
      "requests",
      "serverless"
    ]
  },
  {
    "title": "EKS vs GKE vs AKS cost: a practical comparison checklist (beyond node price)",
    "description": "Compare managed Kubernetes costs across EKS, GKE, and AKS by modeling the same line items: nodes, control plane, load balancers, storage, observability, and egress. Includes a worksheet template and validation steps for baseline vs peak.",
    "canonicalPath": "/guides/eks-vs-gke-vs-aks-cost",
    "category": "Kubernetes",
    "slug": "eks-vs-gke-vs-aks-cost",
    "topics": [
      "egress",
      "kubernetes",
      "load-balancing",
      "storage"
    ]
  },
  {
    "title": "Kubernetes Cost Calculator: what to include (nodes, storage, egress, observability)",
    "description": "A practical checklist for estimating Kubernetes costs: node compute, control plane, load balancers, storage, egress, and observability. Includes a fast workflow and common pitfalls.",
    "canonicalPath": "/guides/kubernetes-cost-calculator",
    "category": "Kubernetes",
    "slug": "kubernetes-cost-calculator",
    "topics": [
      "compute",
      "egress",
      "kubernetes",
      "load-balancing",
      "storage"
    ]
  },
  {
    "title": "Kubernetes cost model beyond nodes: the checklist most teams miss",
    "description": "A practical Kubernetes cost model checklist: control plane, load balancers, storage, logs/metrics, and egress - plus links to calculators to estimate each part.",
    "canonicalPath": "/guides/kubernetes-cost-model-beyond-nodes",
    "category": "Kubernetes",
    "slug": "kubernetes-cost-model-beyond-nodes",
    "topics": [
      "egress",
      "kubernetes",
      "load-balancing",
      "logging",
      "metrics",
      "storage"
    ]
  },
  {
    "title": "Kubernetes costs explained: nodes, egress, load balancers, and observability",
    "description": "A practical Kubernetes cost model: node baseline, cluster add-ons, load balancers, egress/data transfer, and logs/metrics. Includes the most common mistakes and the best calculators.",
    "canonicalPath": "/guides/kubernetes-costs",
    "category": "Kubernetes",
    "slug": "kubernetes-costs",
    "topics": [
      "egress",
      "kubernetes",
      "load-balancing",
      "logging",
      "metrics"
    ]
  },
  {
    "title": "Kubernetes requests & limits: practical sizing (and cost impact)",
    "description": "How to size clusters from requests, choose allocatable headroom, and use limits to reason about burst risk - with a calculator and common pitfalls.",
    "canonicalPath": "/guides/kubernetes-requests-limits",
    "category": "Kubernetes",
    "slug": "kubernetes-requests-limits",
    "topics": [
      "kubernetes",
      "requests"
    ]
  },
  {
    "title": "Kubernetes requests vs limits: why requests drive node count",
    "description": "A practical explanation of Kubernetes requests vs limits for capacity planning and cost estimation, with common mistakes and quick sizing guidance.",
    "canonicalPath": "/guides/kubernetes-requests-vs-limits-for-sizing",
    "category": "Kubernetes",
    "slug": "kubernetes-requests-vs-limits-for-sizing",
    "topics": [
      "kubernetes",
      "requests"
    ]
  },
  {
    "title": "Estimate log ingestion volume (GB/day): fast methods + validation",
    "description": "How to estimate log ingestion volume in GB/day from billing exports, from events/sec × bytes/event, or from throughput. Includes common pitfalls (duplicates, verbose debug logs, multiline events) and next steps to convert volume into dollars.",
    "canonicalPath": "/guides/estimate-log-ingestion-gb-per-day",
    "category": "Logging",
    "slug": "estimate-log-ingestion-gb-per-day",
    "topics": [
      "logging"
    ]
  },
  {
    "title": "Estimating log costs: ingestion, retention, and scan/search",
    "description": "A practical guide to modeling log bills: ingestion vs retention (GB-month), steady state, scan/search pricing, and the fastest levers to reduce cost.",
    "canonicalPath": "/guides/log-costs",
    "category": "Logging",
    "slug": "log-costs",
    "topics": [
      "backup",
      "logging"
    ]
  },
  {
    "title": "Log retention storage cost: steady-state GB-month explained",
    "description": "How log retention turns GB/day into stored GB-month cost. Learn the steady-state model, retention tiers, and the fastest levers to reduce long-term log spend.",
    "canonicalPath": "/guides/log-retention-storage-cost",
    "category": "Logging",
    "slug": "log-retention-storage-cost",
    "topics": [
      "backup",
      "logging",
      "storage"
    ]
  },
  {
    "title": "Network transfer costs explained (egress, cross-region, cross-AZ)",
    "description": "A practical guide to network transfer costs: how to model internet egress, cross-region transfer, cross-AZ traffic, and CDN cache fill. Includes estimation steps and validation tips.",
    "canonicalPath": "/guides/network-transfer-costs",
    "category": "Networking",
    "slug": "network-transfer-costs",
    "topics": [
      "cdn",
      "egress"
    ]
  },
  {
    "title": "Understanding cloud egress costs",
    "description": "A practical guide to estimating egress: units, where bandwidth shows up, quick estimation formulas, and common billing pitfalls.",
    "canonicalPath": "/guides/egress-costs",
    "category": "Networking",
    "slug": "egress-costs",
    "topics": [
      "egress"
    ]
  },
  {
    "title": "Request-based pricing explained: how to estimate requests and avoid surprises",
    "description": "A practical framework for request-based cloud pricing: convert RPS to monthly requests, model retries and fan-out, and avoid unit mistakes (per 10k vs per 1M).",
    "canonicalPath": "/guides/requests-costs",
    "category": "Requests",
    "slug": "requests-costs",
    "topics": [
      "requests"
    ]
  },
  {
    "title": "Copy storage pricing: what you pay for when data moves",
    "description": "A practical guide to pricing storage copy operations (cross-region copy, replication, backups) across S3-like object storage: transfer, requests, and extra storage.",
    "canonicalPath": "/guides/copy-storage-pricing",
    "category": "Storage",
    "slug": "copy-storage-pricing",
    "topics": [
      "backup",
      "egress",
      "requests",
      "storage"
    ]
  },
  {
    "title": "S3 CRR vs SRR cost: what changes (transfer, storage, requests)",
    "description": "A practical cost comparison of S3 cross-region replication (CRR) vs same-region replication (SRR). Compare transfer/feature fees, extra replica storage, and request costs - with calculators.",
    "canonicalPath": "/guides/s3-crr-vs-srr-cost",
    "category": "Storage",
    "slug": "s3-crr-vs-srr-cost",
    "topics": [
      "egress",
      "requests",
      "storage"
    ]
  },
  {
    "title": "S3 pricing explained: storage vs requests vs egress",
    "description": "A practical breakdown of S3-like object storage pricing: GB-month storage, request fees, and data egress - plus how to estimate each without missing hidden line items.",
    "canonicalPath": "/guides/s3-pricing-explained",
    "category": "Storage",
    "slug": "s3-pricing-explained",
    "topics": [
      "egress",
      "requests",
      "storage"
    ]
  },
  {
    "title": "S3 replication cost: how to estimate cross-region replication",
    "description": "A practical guide to estimating S3 replication cost: what data volume to count, which fees to expect, and how to model replica storage, requests, and transfer. Includes a fast checklist.",
    "canonicalPath": "/guides/s3-replication-cost",
    "category": "Storage",
    "slug": "s3-replication-cost",
    "topics": [
      "egress",
      "requests",
      "storage"
    ]
  },
  {
    "title": "Storage costs explained: GB-month, requests, and replication",
    "description": "A practical guide to storage cost modeling: GB-month, request fees, retention, replication, and transfer. Includes estimation steps and common pitfalls.",
    "canonicalPath": "/guides/storage-costs",
    "category": "Storage",
    "slug": "storage-costs",
    "topics": [
      "backup",
      "egress",
      "requests",
      "storage"
    ]
  }
];
